### ISSUE TITLE
Jumpjet was dragged out (looked fine in list), became damaged when placed on mech

### ISSUE THREAD

**Issue by m22spencer** [m22spencer/BattletechPerformanceFix#17]
![thekooleagledamagedheatsink](https://user-images.githubusercontent.com/844938/43937853-daf58f94-9c25-11e8-8267-765a9fdc462f.PNG)

**Comment by CptMoore** [comment]
Damaged components can be dismounted and surivive in statcollection of simgame

**Comment by m22spencer** [comment]
Sounds like I need to show the items as damaged in the mechlist when they are damaged then.

Thanks
