### ISSUE TITLE
Dupebug.

### ISSUE THREAD

**Issue by Tubben** [m22spencer/BattletechPerformanceFix#24]
If you have an broken item in your inventory, it's possible to dupe it. Following steps will do that:

1.)
![image](https://user-images.githubusercontent.com/10608926/44398276-9bcb8b80-a543-11e8-8fbd-c89a20e2ab73.png)

2.)
![image](https://user-images.githubusercontent.com/10608926/44398357-ddf4cd00-a543-11e8-9e9a-e51db9c22394.png)

3.)
![image](https://user-images.githubusercontent.com/10608926/44398442-201e0e80-a544-11e8-977b-b407b5dbf0f0.png)

[BattletechPerformanceFix.log](https://github.com/m22spencer/BattletechPerformanceFix/files/2306015/BattletechPerformanceFix.log)

Thanks for your time :-)

**Comment by m22spencer** [comment]
Possibly related to d059b0c

**Comment by CptMoore** [comment]
Tubben you cheater :D finally I see a damaged component .. never have until now

**Comment by m22spencer** [comment]
I don't think the vanilla game shows them.  
Notice that when one PPC is dragged out, it removes it from the non-broken item (6 -> 5)

**Comment by Tubben** [comment]
Ok, rechecked it ingame. you drag the broken item, but he reduce the nonbroken itemstack.
If you remove enough, so that the NONbroken stack is empty, he takes from the broken stack. If you then strip your mech, the BROKEN stack not be 1 anymore, but the amount of items you had.

So, it's not really an bug and no dupe bug at all.

8 non broken, 1 broken
![image](https://user-images.githubusercontent.com/10608926/44430239-61d9a400-a59a-11e8-84a6-7ba6e58007e2.png)

![image](https://user-images.githubusercontent.com/10608926/44430322-9ea59b00-a59a-11e8-9800-5221038c2961.png)


![image](https://user-images.githubusercontent.com/10608926/44430379-c0068700-a59a-11e8-9de4-57a8378e2e81.png)

**Comment by CptMoore** [comment]
so damaged isnt supported at all, either fix the feature or remove it? and who? is this the mod that enabled this feature?

**Comment by m22spencer** [comment]
This is a result of fixing damaged items being hidden (d059b0c).

Either way, it's broken.

**Comment by m22spencer** [comment]
[BattletechPerformanceFix-dupefix.zip](https://github.com/m22spencer/BattletechPerformanceFix/files/2325934/BattletechPerformanceFix-dupefix.zip)

Can you test and report back?

**Comment by m22spencer** [comment]
Great, thanks for the report.

**Comment by Tubben** [comment]
Hey J

 

Just installed the BT 1.2.1-347R Build together with that pfix. And tested some stuff (dragging items from left to right, visit shop, checked broken items).. 

Looked good. Everything worked.

 

Can I give LA that version? Or even better, are you going to push a new release? J

 

Best regards,

Tubben

 

 

Von: Matthew Spencer <notifications@github.com> 
Gesendet: Dienstag, 28. August 2018 09:45
An: m22spencer/BattletechPerformanceFix <BattletechPerformanceFix@noreply.github.com>
Cc: Tubben <naladdar@googlemail.com>; Author <author@noreply.github.com>
Betreff: Re: [m22spencer/BattletechPerformanceFix] Dupebug. (#24)

 

Great, thanks for the report.
