### ISSUE TITLE
Issue with Skip Prologue and experimentalLazyRoomInitialization

### ISSUE THREAD

**Issue by Red1812** [m22spencer/BattletechPerformanceFix#26]
Hello,
I found an issue with the latest version of BattletechPerformanceFix 1.2.3 (didn't check other version).
When you create a new custom campaign and check the Skip Prologue option if you have experimentalLazyRoomInitialization to true it will skip the first mission ("Three Years Later") to go directly to the dropship.
Everything seems to work fine until you try to advance time and nothing happens.

**Comment by Red1812** [comment]
I updated to BTML v0.5.0alpha1 and ModTek v0.3.1 and the issue remains.
Note that once you passed that mission activating experimentalLazyRoomInitialization seems to be working fine.

**Comment by Red1812** [comment]
You recommend not using the feature at all?
Because the difference in game is amazing and I'd rather take 10s to activate it afterward than not using it.

**Comment by m22spencer** [comment]
There may be other areas where it causes issues, I haven't had a chance to test it much. You're welcome to use it, just be aware of this.

**Comment by m22spencer** [comment]
Fixed with fe98d4b
