### ISSUE TITLE
MDDB_InMemoryCache on linux

### ISSUE THREAD

**Issue by sozforex** [m22spencer/BattletechPerformanceFix#39]
If you try to enable MDDB_InMemoryCache feature on linux, it will not work by default.
To make it work, you need to compile libSQLite.Interop.so and place it inside BATTLETECH directory (game root).
Here is a guide about compiling libSQLite.Interop.so :
http://blog.wezeku.com/2016/10/09/using-system-data-sqlite-under-linux-and-mono/

UPD: Compiled libSQLite.Interop.so by me
[libSQLite.Interop.zip](https://github.com/m22spencer/BattletechPerformanceFix/files/2730606/libSQLite.Interop.zip)
Do not know if it will work for everyone, to try - unpack in game root directory ("BATTLETECH"). After that, running the game should not add any errors/exceptions related to MDDB_InMemoryCache and SQLite in mods/BattletechPerformanceFix/BattletechPerformanceFix.log at startup.

**Comment by m22spencer** [comment]
Yep, the Interop distributed is windows only.  I'm currently not setup to build the .so/.dylib, which is why it hasn't been done yet.

MDDB patch is only a temporary one, as the proper fix (which is even faster) requires modifying some 80+ callsites.   Granted, it's been out long enough that it's not really "temporary".

**Comment by sozforex** [comment]
I'll close this issue - I just wanted to provide some info for linux users, and did not know where it is better to do it. If you need any help related to compiling/testing on linux - send me a message.
Thanks for your work =)

**Comment by m22spencer** [comment]
Lets leave it open for now.   I'm normally a linux user, so I'd like to see this fixed as well.

I think for starters, setting up the LD_LIBRARY_PATH will simplify a bit, until I can get around to building a .so

If you have a built version, feel free to link it here and point people to it.  Anything going into the repo I'd prefer to compile directly.

**Comment by sozforex** [comment]
To upload it here, I had to compress it.
[libSQLite.Interop.zip](https://github.com/m22spencer/BattletechPerformanceFix/files/2730606/libSQLite.Interop.zip)

**Comment by m22spencer** [comment]
The MDDB issue does not seem to occur on mac.   Out of curiosity: What filesystem type are you using?

**Comment by sozforex** [comment]
ext4. I'm pretty sure that filesystem has nothing to do with this.
OS: gentoo (unstable)
This is how this error looks in log, if i do not add libSQLite.Interop.so to the game folder:

```
[Warning] SQlite dependencies not found. Aborting MDDB patch.
[Exception] System.DllNotFoundException: SQLite.Interop.dll
  at (wrapper managed-to-native) System.Data.SQLite.UnsafeNativeMethods:sqlite3_config_none (System.Data.SQLite.SQLiteConfigOpsEnum)
  at System.Data.SQLite.SQLite3.StaticIsInitialized () [0x00000] in <filename unknown>:0
  at System.Data.SQLite.SQLiteLog.Initialize (System.String className) [0x00000] in <filename unknown>:0
  at System.Data.SQLite.SQLiteConnection..ctor (System.String connectionString, Boolean parseViaFramework) [0x00000] in <filename unknown>:0
  at System.Data.SQLite.SQLiteConnection..ctor (System.String connectionString) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteConnection:.ctor (string)
  at BattletechPerformanceFix.MDDB_InMemoryCache.Activate () [0x00000] in <filename unknown>:0
[Error] Failed to activate feature BattletechPerformanceFix.MDDB_InMemoryCache with:
 System.Exception: MDDB Patch aborted (This is okay, you just won't get the performance improvement)
  at BattletechPerformanceFix.MDDB_InMemoryCache.Activate () [0x00000] in <filename unknown>:0
  at BattletechPerformanceFix.Main+<>c.<Start>b__10_1 () [0x00000] in <filename unknown>:0
```

**Comment by m22spencer** [comment]
One of the ModTek devs is on Mac, and we found out that the MDDB isn't slow at all for him.  So after doing another check on windows, it's the NTFS journal log that gets hit, not so much the MDDB.

I've never actually tested on Linux. Is the HBS logo hang (without bfix) a thing under linux/ext4?

Re: errors - While it looks pretty bad in the logs, that's inert. It just means the patch won't get activated.

**Comment by sozforex** [comment]
With in memory DB path enabled, population of modtek database after clean install takes 4 minutes.
With patch disabled, it takes 23 minutes.

I do not know about what other speedups it provides (I have not played without it).
I do not know anything about HBS logo hang.

It is possible, that disabling file contents indexing on windows for modtek database file or for drive where game is installed will speedup MDDB with MDDB_InMemoryCache disabled.
But I see no reason to not to enable this patch (it will provide speedup in any case, and does not require a lot of RAM (something like 10MB?)).

If you will want to test on linux some day, search "script by b2cc" on roguetech-support discord channel it will help to find and fix problems with paths in mods folder.

**Comment by m22spencer** [comment]
No longer relevant (vanilla implemented this)
