### ISSUE TITLE
Turrets are being seen as vehicles/mechs in missions

### ISSUE THREAD

**Issue by xeryx01** [m22spencer/BattletechPerformanceFix#45]

**Comment by xeryx01** [comment]
When I run this mod, my turret chassis changes maybe causing the mod to see them as vehicles, something is getting mis-categorized.  about 20% of the time during missions I will see turret in the palce of vehicles or mechs.  I have customized turrets and I can only assume this is the cause, because when I remove them the issue goes away with this mod running. However, since my custom turrets are important to my mod, I have elected to exclude this mod from working with XAI Battletech.  Can you please look at this issue.  By running my mod and look for any other issues as well, specifically the mechlab. I have tons of weapons and upgrades and ammo.

**Comment by m22spencer** [comment]
bfix in 1.4 does not touch tags or spawning.  The only two features which are in any way related to battles are ContractsLagFix & ExtraLogging, which you can disable in the settings.  It is extremely unlikely that bfix is your issue.

If you want me to investigate further, I need you to attach logs.
