### ISSUE TITLE
Does not work on 1.8.1

### ISSUE THREAD

**Issue by Matt-Ceb** [m22spencer/BattletechPerformanceFix#53]
Flat out fails to load, with an error message from ModTek that BT Performance Fix can not be started during the start-up of BATTLETECH.

**Comment by m22spencer** [comment]
If you attach logs, I'll be happy to help you.  With just the provided information there is nothing I can do.

**Comment by Matt-Ceb** [comment]
Oh, sorry!

Here are the three logs after the last start-up.

And here's how the game greets me, when I have the mod enabled:
https://steamcommunity.com/sharedfiles/filedetails/?id=1960860250 (link to steam screenshot.)

[ModTek.log](https://github.com/m22spencer/BattletechPerformanceFix/files/4023741/ModTek.log)
[ModTek_runtime_log.txt](https://github.com/m22spencer/BattletechPerformanceFix/files/4023742/ModTek_runtime_log.txt)
[harmony_summary.log](https://github.com/m22spencer/BattletechPerformanceFix/files/4023743/harmony_summary.log)

**Comment by m22spencer** [comment]
`Error: DLL specified (C:\STEAM-SSD\steamapps\common\BATTLETECH\Mods\BattletechPerformanceFix\BattletechPerformanceFix.dll), but it's missing! Aborting load.`

Your install is busted. Bfix isn't loading because it doesn't exist.  Redownload latest release from github.

**Comment by Matt-Ceb** [comment]
Mh. I just looked over the github, and the "BattletechPerformanceFix.dll" doesn't exist in any of the  folders found here. 

Am I missing something? Is there another github page I need to get the files from? (I might be actually missing how to properly download it from github, in that case.) 

I got the "BattletechPerformanceFix" folder and put it in my Battletech Mods folder.

**Comment by Matt-Ceb** [comment]
And in that folder, the only files are those:

 	SQLite.Interop.dll
	Settings.json
	System.Data.SQLite.Linq.dll
	System.Data.SQLite.dll
	mod.json

**Comment by m22spencer** [comment]
Always use the latest release from here

https://github.com/m22spencer/BattletechPerformanceFix/releases

**Comment by Matt-Ceb** [comment]
... That's what I've been doing yes. Sorry, I'm dumb. :-/

Thank you for your help and patience!

**Comment by Matt-Ceb** [comment]
Okay, just tested it.
It loads, it works and it's an amazing speed upgrade. 

Again, thank you very much!

**Comment by m22spencer** [comment]
No problem. Glad your issue is fixed.
